ii:
  server: 192.168.255.86

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    inetutils:
      preferred-networks:
        - "192.168.255"

hst:
  auth:
    enable-cookie: true

eureka:
  client:
    enabled: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
