ii:
  server: 192.168.255.86

hst:
  auth:
    enable-cookie: true

spring:
  cloud:
    inetutils:
      preferred-networks:
        - "192.168.255"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
