hst:
  auth:
    enable-cookie: true

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
